permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4 #6
comments: false
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Mug Jekyll theme
title: Mug
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, mug, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/mug"
domain_name: nandomoreira.me
repo: https://github.com/ismail-syed
disqus_shortname: "nandothemes"

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
